//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektinRestPalvelu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JuomasivuDBEntities : DbContext
    {
        public JuomasivuDBEntities()
            : base("name=JuomasivuDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arvostelut> Arvostelut { get; set; }
        public virtual DbSet<Juomat> Juomat { get; set; }
        public virtual DbSet<Kayttajat> Kayttajat { get; set; }
    }
}
